// <auto-generated />
using System;
using BlazorREPRODEV.App.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorREPRODEV.App.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210613081104_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.ComponentSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("ComponentSubjects");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.DatabaseConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLoaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialDataLoaded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConfigs");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Choice1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ComponentSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("InActive")
                        .HasColumnType("int");

                    b.Property<string>("MyQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentSubjectId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.RegisteredStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsAccepted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegisteredStudents");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InActive")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.ComponentSubject", b =>
                {
                    b.HasOne("BlazorREPRODEV.App.Shared.Models.Subject", null)
                        .WithMany("ComponentSubjects")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.Question", b =>
                {
                    b.HasOne("BlazorREPRODEV.App.Shared.Models.ComponentSubject", null)
                        .WithMany("Questions")
                        .HasForeignKey("ComponentSubjectId");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.RegisteredStudent", b =>
                {
                    b.HasOne("BlazorREPRODEV.App.Shared.Models.UserAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.ComponentSubject", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BlazorREPRODEV.App.Shared.Models.Subject", b =>
                {
                    b.Navigation("ComponentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
